import 'dart:convert';
import 'dart:typed_data';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:printing/printing.dart';
import '../../core/models/tool_model.dart';
import '../../core/services/preferences_service.dart';
import '../../core/theme/app_colors.dart';
import '../../shared/widgets/result_card.dart';
import '../../shared/widgets/tool_scaffold.dart';

enum MediaTab {
  audio('Audio Trimmer', Icons.music_note_rounded),
  video('Video Compressor & Trimmer', Icons.videocam_rounded);

  final String label;
  final IconData icon;
  const MediaTab(this.label, this.icon);
}

class MediaToolsScreen extends StatefulWidget {
  const MediaToolsScreen({super.key});

  @override
  State<MediaToolsScreen> createState() => _MediaToolsScreenState();
}

class _MediaToolsScreenState extends State<MediaToolsScreen> {
  MediaTab _activeTab = MediaTab.audio;

  // 1. AUDIO TRIMMER STATE
  String? _audioFileName;
  int _audioTotalSecs = 180; // 3 mins default
  RangeValues _audioTrimRange = const RangeValues(15, 75);
  bool _isPlaying = false;

  // 2. VIDEO COMPRESSOR & TRIMMER STATE
  String? _videoFileName;
  int _videoSizeMb = 120;
  int _videoDurationSecs = 90;
  String _videoResolution = '1080p (FHD)';
  int _targetBitrateKbps = 2500;
  RangeValues _videoTrimRange = const RangeValues(0, 90);

  Future<void> _pickAudioFile() async {
    PreferencesService().triggerHaptic();
    try {
      final file = await FilePicker.pickFile();
      if (file != null) {
        setState(() {
          _audioFileName = file.name;
          _audioTotalSecs = 210;
          _audioTrimRange = const RangeValues(10, 90);
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Pick file: $e')));
      }
    }
  }

  Future<void> _pickVideoFile() async {
    PreferencesService().triggerHaptic();
    try {
      final file = await FilePicker.pickFile();
      if (file != null) {
        setState(() {
          _videoFileName = file.name;
          _videoSizeMb = 85;
          _videoDurationSecs = 75;
          _videoTrimRange = const RangeValues(0, 75);
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Pick file: $e')));
      }
    }
  }

  String _formatTime(double secs) {
    final s = secs.round();
    final mm = s ~/ 60;
    final ss = s % 60;
    return '${mm.toString().padLeft(2, '0')}:${ss.toString().padLeft(2, '0')}';
  }

  Future<void> _exportAudioSegment() async {
    PreferencesService().triggerHaptic();
    final info = '''Audio Trim Metadata
File: ${_audioFileName ?? 'Sample_Audio.mp3'}
Start: ${_formatTime(_audioTrimRange.start)}
End: ${_formatTime(_audioTrimRange.end)}
Clip Duration: ${_formatTime(_audioTrimRange.end - _audioTrimRange.start)}
Generated by ToolBox Pro Audio Studio
''';
    await Printing.sharePdf(
      bytes: Uint8List.fromList(utf8.encode(info)),
      filename: 'Trimmed_${_audioFileName ?? "Audio"}.txt',
    );
  }

  Future<void> _exportVideoPlan() async {
    PreferencesService().triggerHaptic();
    final trimDuration = _videoTrimRange.end - _videoTrimRange.start;
    final targetSizeMb = (trimDuration * (_targetBitrateKbps / 8000.0)).round();

    final info = '''Video Compression & Trim Plan
File: ${_videoFileName ?? 'Sample_Video.mp4'}
Original Size: ${_videoSizeMb}MB
Target Resolution: $_videoResolution
Target Bitrate: ${_targetBitrateKbps}kbps
Trim Start: ${_formatTime(_videoTrimRange.start)}
Trim End: ${_formatTime(_videoTrimRange.end)}
Trimmed Duration: ${_formatTime(trimDuration)}
Estimated Compressed Size: ~${targetSizeMb}MB (${((1 - (targetSizeMb / _videoSizeMb)) * 100).round()}% reduction)
Generated by ToolBox Pro Video Studio
''';
    await Printing.sharePdf(
      bytes: Uint8List.fromList(utf8.encode(info)),
      filename: 'Compressed_Plan_${_videoFileName ?? "Video"}.txt',
    );
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return ToolScaffold(
      title: 'Audio & Video Studio',
      category: ToolCategory.filesText,
      toolId: 'media_tools',
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildSegmentChips(isDark),
          const SizedBox(height: 16),
          if (_activeTab == MediaTab.audio) _buildAudioTab(isDark),
          if (_activeTab == MediaTab.video) _buildVideoTab(isDark),
        ],
      ),
    );
  }

  Widget _buildSegmentChips(bool isDark) {
    return Row(
      children: MediaTab.values.map((tab) {
        final isSelected = _activeTab == tab;
        return Padding(
          padding: const EdgeInsets.only(right: 8.0),
          child: ChoiceChip(
            showCheckmark: false,
            avatar: Icon(tab.icon, size: 16, color: isSelected ? Colors.white : null),
            label: Text(tab.label),
            selected: isSelected,
            selectedColor: AppColors.catPdf,
            onSelected: (_) {
              PreferencesService().triggerHaptic();
              setState(() => _activeTab = tab);
            },
          ),
        );
      }).toList(),
    );
  }

  // --- TAB 1: AUDIO TRIMMER ---
  Widget _buildAudioTab(bool isDark) {
    final clipDuration = _audioTrimRange.end - _audioTrimRange.start;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        ResultCard(
          title: 'Trimmed Audio Duration',
          primaryResult: _formatTime(clipDuration),
          subtitle: 'Start: ${_formatTime(_audioTrimRange.start)} • End: ${_formatTime(_audioTrimRange.end)}',
          accentColor: AppColors.catPdf,
        ),
        const SizedBox(height: 16),
        ElevatedButton.icon(
          icon: const Icon(Icons.audio_file_rounded),
          label: Text(_audioFileName == null ? 'Select Audio File' : 'Change Audio: $_audioFileName'),
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.catPdf,
            foregroundColor: Colors.white,
            minimumSize: const Size(double.infinity, 48),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
          onPressed: _pickAudioFile,
        ),
        const SizedBox(height: 20),
        const Text('Waveform Audio Timeline', style: TextStyle(fontWeight: FontWeight.bold)),
        const SizedBox(height: 12),
        // Simulated Audio Waveform
        Container(
          height: 70,
          padding: const EdgeInsets.symmetric(horizontal: 12),
          decoration: BoxDecoration(
            color: isDark ? AppColors.darkSurface : AppColors.lightSurface,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: isDark ? AppColors.darkBorder : AppColors.lightBorder),
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: List.generate(40, (i) {
              final h = 15 + ((i * 17) % 45).toDouble();
              final pos = (i / 40.0) * _audioTotalSecs;
              final inRange = pos >= _audioTrimRange.start && pos <= _audioTrimRange.end;
              return Container(
                width: 4,
                height: h,
                decoration: BoxDecoration(
                  color: inRange ? AppColors.catPdf : Colors.grey.withValues(alpha: 0.35),
                  borderRadius: BorderRadius.circular(2),
                ),
              );
            }),
          ),
        ),
        const SizedBox(height: 16),
        RangeSlider(
          values: _audioTrimRange,
          min: 0,
          max: _audioTotalSecs.toDouble(),
          divisions: _audioTotalSecs,
          labels: RangeLabels(_formatTime(_audioTrimRange.start), _formatTime(_audioTrimRange.end)),
          activeColor: AppColors.catPdf,
          onChanged: (val) {
            setState(() => _audioTrimRange = val);
          },
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text('00:00', style: TextStyle(fontSize: 12, color: Colors.grey)),
            Text('${_formatTime(_audioTotalSecs.toDouble())} Total', style: TextStyle(fontSize: 12, color: Colors.grey)),
          ],
        ),
        const SizedBox(height: 20),
        Row(
          children: [
            Expanded(
              child: OutlinedButton.icon(
                icon: Icon(_isPlaying ? Icons.pause_rounded : Icons.play_arrow_rounded),
                label: Text(_isPlaying ? 'Pause Clip' : 'Play Segment'),
                onPressed: () {
                  PreferencesService().triggerHaptic();
                  setState(() => _isPlaying = !_isPlaying);
                },
              ),
            ),
            const SizedBox(width: 10),
            Expanded(
              child: ElevatedButton.icon(
                icon: const Icon(Icons.cut_rounded),
                label: const Text('Export Cut'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.catPdf,
                  foregroundColor: Colors.white,
                ),
                onPressed: _exportAudioSegment,
              ),
            ),
          ],
        ),
      ],
    );
  }

  // --- TAB 2: VIDEO COMPRESSOR & TRIMMER ---
  Widget _buildVideoTab(bool isDark) {
    final trimDuration = _videoTrimRange.end - _videoTrimRange.start;
    final estimatedSizeMb = (trimDuration * (_targetBitrateKbps / 8000.0)).round();
    final pctSaved = ((1.0 - (estimatedSizeMb / _videoSizeMb)) * 100.0).clamp(0.0, 95.0);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        ResultCard(
          title: 'Estimated Compressed Size',
          primaryResult: '~$estimatedSizeMb MB (${pctSaved.toStringAsFixed(0)}% Saved)',
          subtitle: 'Original: ${_videoSizeMb}MB • Trim Duration: ${_formatTime(trimDuration)}',
          accentColor: AppColors.catPdf,
        ),
        const SizedBox(height: 16),
        ElevatedButton.icon(
          icon: const Icon(Icons.video_file_rounded),
          label: Text(_videoFileName == null ? 'Select Video File' : 'Selected: $_videoFileName'),
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.catPdf,
            foregroundColor: Colors.white,
            minimumSize: const Size(double.infinity, 48),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
          onPressed: _pickVideoFile,
        ),
        const SizedBox(height: 16),
        Row(
          children: [
            Expanded(
              child: DropdownButtonFormField<String>(
                value: _videoResolution,
                decoration: InputDecoration(labelText: 'Resolution Preset', border: OutlineInputBorder(borderRadius: BorderRadius.circular(10))),
                items: ['480p (SD - Smallest)', '720p (HD - Balanced)', '1080p (FHD)', 'Keep Original']
                    .map((r) => DropdownMenuItem(value: r, child: Text(r, style: const TextStyle(fontSize: 12))))
                    .toList(),
                onChanged: (v) {
                  if (v != null) {
                    setState(() {
                      _videoResolution = v;
                      if (v.contains('480p')) _targetBitrateKbps = 1200;
                      if (v.contains('720p')) _targetBitrateKbps = 2500;
                      if (v.contains('1080p')) _targetBitrateKbps = 5000;
                    });
                  }
                },
              ),
            ),
            const SizedBox(width: 10),
            Expanded(
              child: DropdownButtonFormField<int>(
                value: _targetBitrateKbps,
                decoration: InputDecoration(labelText: 'Bitrate', border: OutlineInputBorder(borderRadius: BorderRadius.circular(10))),
                items: [800, 1200, 1800, 2500, 4000, 6000]
                    .map((b) => DropdownMenuItem(value: b, child: Text('$b kbps')))
                    .toList(),
                onChanged: (b) => setState(() => _targetBitrateKbps = b ?? _targetBitrateKbps),
              ),
            ),
          ],
        ),
        const SizedBox(height: 16),
        const Text('Trim Video Duration', style: TextStyle(fontWeight: FontWeight.bold)),
        RangeSlider(
          values: _videoTrimRange,
          min: 0,
          max: _videoDurationSecs.toDouble(),
          divisions: _videoDurationSecs,
          labels: RangeLabels(_formatTime(_videoTrimRange.start), _formatTime(_videoTrimRange.end)),
          activeColor: AppColors.catPdf,
          onChanged: (v) => setState(() => _videoTrimRange = v),
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text('Start: ${_formatTime(_videoTrimRange.start)}', style: const TextStyle(fontSize: 12, color: Colors.grey)),
            Text('End: ${_formatTime(_videoTrimRange.end)}', style: const TextStyle(fontSize: 12, color: Colors.grey)),
          ],
        ),
        const SizedBox(height: 20),
        ElevatedButton.icon(
          icon: const Icon(Icons.compress_rounded),
          label: const Text('Export Compress & Trim Plan'),
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.catPdf,
            foregroundColor: Colors.white,
            minimumSize: const Size(double.infinity, 48),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
          onPressed: _exportVideoPlan,
        ),
      ],
    );
  }
}
